/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Compusophlets__factory } from "./Compusophlets__factory";
export { GenerativePFP__factory } from "./GenerativePFP__factory";
